restaurant/urls.py
from django.urls import path
from . import views

app_name='restaurant'

urlpatterns=[
    path('',views.index,name='home'),
    path('register/',views.registerUser,name='register'),
    path('login/',views.loginUser,name='login'),
    path('logout/',views.logoutUser,name='logout'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('delete-address/<int:id>',views.deleteAddress,name='delete-address'),
    path('admin-dashboard/',views.adminDashboard,name='admin-dashboard'),
    path('subadmin-dashboard/',views.subadminDashboard,name='subadmin-dashboard'),
    path('add-to-subadmin/<int:id>',views.addToSubadmin,name='add-to-subadmin'),
    path('user/<int:id>',views.userDetail,name='view-user'),
    path('delete-user/<int:id>',views.userDelete,name='delete-user'),
    path('add-restaurant',views.addRestaurant,name='add-restaurant'),
    path('restaurant/<int:resID>/menu/',views.restaurantMenu,name='menu'),
    path('delete-food/<int:id>',views.deleteFood,name='delete-food'),
    path('update-food/<int:id>',views.updateFood,name='update-food'),
    path('delete-restaurant/<int:id>',views.deleteRestaurant,name='delete-res'),
    path('change_password/',views.changePassword,name='change_password'),
    path('add-address/',views.addAddress,name='add-address'),
    path('search/restaurant/',views.searchRestaurant,name='search'),
]

rms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('restaurant.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from .manager import UserManager
from django.conf import settings
from geopy.geocoders import Nominatim

#Custom User Model
class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    full_name = models.CharField(_('full name'), max_length=30)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(default=False)
    is_subadmin=models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    created_by=models.CharField(max_length=100,null=True,blank=True)
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        return self.full_name

class UserAddresses(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='address')
    address=models.TextField(max_length=1000)
    pincode=models.CharField(max_length=30,null=True)
    lat=models.CharField(max_length=50,null=True,blank=True)
    lng=models.CharField(max_length=50,null=True,blank=True)

    def save(self, *args, **kwargs):
        geolocator = Nominatim(user_agent="geoapiExercises")
        location = geolocator.geocode(int(self.pincode))
        self.lat = location.latitude
        self.lng = location.longitude
        super(UserAddresses, self).save(*args, **kwargs)

    def __str__(self):  
        return self.address[0:30]

class Restaurant(models.Model):

    created_by=models.ForeignKey(
        settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    name=models.CharField(max_length=300)
    address=models.TextField(max_length=500)
    pincode=models.CharField(max_length=30,null=True)
    lat=models.CharField(max_length=50,null=True,blank=True)
    lng=models.CharField(max_length=50,null=True,blank=True)
    image=models.ImageField(upload_to='restaurant/')
    created_at=models.DateTimeField(auto_now_add=True,null=True)
    updated_at=models.DateTimeField(auto_now=True,null=True)

    def save(self, *args, **kwargs):
        geolocator = Nominatim(user_agent="geoapiExercises")
        location = geolocator.geocode(int(self.pincode))
        self.lat = location.latitude
        self.lng = location.longitude
        super(Restaurant, self).save(*args, **kwargs)

    def __str__(self):
        return self.name
        
class Food(models.Model):
    restaurant=models.ForeignKey(Restaurant,on_delete=models.CASCADE,null=True,related_name='food')
    name=models.CharField(max_length=300,null=True)
    price=models.FloatField(null=True)
    description=models.TextField(max_length=500,null=True)
    image=models.ImageField(upload_to='food/',null=True)
    created_at=models.DateTimeField(auto_now_add=True,null=True)
    updated_at=models.DateTimeField(auto_now=True,null=True)

    def __str__(self):
        return self.name

restaurant/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from django.forms import widgets
from django.forms.widgets import PasswordInput, Textarea
from .models import Food, Restaurant, User,UserAddresses

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=PasswordInput,min_length=8,required=True)
    class Meta:
        model=User
        fields=['email','full_name','password']

    def clean_password(self):
        password=self.cleaned_data['password']
        if len(password)<8:
            raise forms.ValidationError("Your password should be at least 8 Characters ")
      
        return password

class UserAddresseForm(forms.ModelForm):
    address=forms.CharField(widget=Textarea(attrs={'cols':40,'rows':4}))
    class Meta:
        model=UserAddresses
        fields=['address','pincode']
    
class RestaurantForm(forms.ModelForm):
    address=forms.CharField(widget=Textarea(attrs={'cols':40,'rows':3}))
    class Meta:
        model=Restaurant
        fields=['name','address','pincode','image']

class FoodForm(forms.ModelForm):
    description=forms.CharField(widget=Textarea(attrs={'cols':40,'rows':2}))
    class Meta:
        model=Food
        fields=['name','price','description','image']

restaurant/views.py
from django import forms
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from restaurant.forms import FoodForm, UserForm,UserAddresseForm,RestaurantForm
from .models import *
from django.core.mail import send_mail  
from geopy.distance import  great_circle
# Create your views here.

def index(request):
    return render(request,'restaurant/index.html')

def registerUser(request):
    if request.user.is_authenticated:
        return redirect('/dashboard/')
    if request.method=='GET':
        form=UserForm(None)
        return render(request,'restaurant/register.html',{'form':form})
    elif request.method=='POST':
        form=UserForm(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            email=form.cleaned_data['email']
            password=form.cleaned_data['password']
            user.set_password(password)
            user.save()
            #send_mail_after_registration(email)
            user=authenticate(email=email,password=password)
            if user is not None:
                if user.is_active:
                    login(request,user)
                    messages.success(request,'Your account has been successfully created.')
                    return redirect('/dashboard/')
                else:
                    return HttpResponse("Oops! Something went wrong, your Account has been deleted/deactivate")
        else:
            return render(request,'restaurant/register.html',{'form':form})
    
"""def send_mail_after_registration(email):
    subject="Your Account has been created successfully"
    message=f'Thank you for sign up.'
    email_from=settings.EMAIL_HOST_USER
    receipent_list=[email]
    send_mail(subject,message,email_from,receipent_list)"""

def loginUser(request):
    if request.method=='GET':
        if request.user.is_authenticated:
            if request.user.is_staff:
                return redirect('/admin-dashboard/')
            elif request.user.is_subadmin:
                return redirect('/subadmin-dashboard/')
            else:
                return redirect('/dashboard/')
        return render(request,'restaurant/login.html')
    elif request.method== 'POST':
        email=request.POST.get('email')
        password=request.POST.get('password')
        if email == '' or password =='':
            return render(request,'restaurant/login.html',{'error_msg':'both are required fields'})
        user=authenticate(email=email,password=password)
        if user is not None:
            if user.is_active:
                if user.is_staff:
                    login(request,user)
                    messages.success(request,'You are successfully logged in.')
                    return redirect('/admin-dashboard/')
                elif user.is_subadmin:
                    login(request,user)
                    messages.success(request,'You are successfully logged in.')
                    return redirect('/subadmin-dashboard/')
                else:
                    login(request,user)
                    messages.success(request,'You are successfully logged in.')
                    return redirect('/dashboard/')
            else:
                return HttpResponse('Your Account has been disabled')
        else:
            return render(request,'restaurant/login.html',{'error_msg':'your username or password is incorrect'})

def logoutUser(request):
    logout(request)
    messages.success(request,'Your are successfully logged out.')
    return redirect('/login/')

@login_required
def dashboard(request):
    if request.method=='GET':
        if request.user.is_authenticated:
            if request.user.is_staff:
                return redirect('/admin-dashboard/')
            elif request.user.is_subadmin:
                return redirect('/subadmin-dashboard/')
        try:
            address_obj=UserAddresses.objects.filter(user=request.user)
            restaurant_list=Restaurant.objects.select_related('created_by').all().order_by('-created_at')
            print(restaurant_list)
        except Exception as e:
            return HttpResponse(e)
        form=UserAddresseForm(None)
        context={
            'form':form,
            'addresses':address_obj,
            'restaurant':restaurant_list
        }
        return render(request,'restaurant/welcome.html',context)
    elif request.method=='POST':
        form=UserAddresseForm(request.POST)
        if form.is_valid():
            address=form.cleaned_data['address']
            pincode=form.cleaned_data['pincode']
            if pincode:
                geolocator = Nominatim(user_agent="geoapiExercises")
                location = geolocator.geocode(int(pincode))
                lat = location.latitude
                lng = location.longitude 

                address_obj=UserAddresses(user=request.user,address=address,pincode=pincode,lat=lat,lng=lng)
                address_obj.save()
                messages.success(request,'adddress has been added')
                return redirect('/dashboard/')
        return render(request,'restaurant/welcome.html',{'form':form})

@login_required
def deleteAddress(request,id):
    delete_obj=UserAddresses.objects.get(user=request.user,id=id)
    delete_obj.delete()
    messages.info(request,'Address has been deleted.')
    if request.user.is_subadmin:
        return redirect('/subadmin-dashboard/')
    else:
        return redirect('/dashboard/')

@login_required
def adminDashboard(request):
    if request.method=='GET':
        if request.user.is_authenticated:
            if not request.user.is_staff:
                if request.user.is_subadmin:
                    return redirect('/subadmin-dashboard/')
                else:
                    return redirect('/dashboard/')
        try:
            user_list=User.objects.all().exclude(email=request.user).order_by('-date_joined')
            restaurant_list=Restaurant.objects.select_related('created_by').all().exclude(created_by=request.user).order_by('-created_at')
            loginUser_restaurant_list=Restaurant.objects.select_related('created_by').filter(created_by=request.user).order_by('-created_at')
            form=UserForm(request.POST or None)
        except Exception as e:
            return HttpResponse(e)
        context={
            'users':user_list,
            'form':form,
            'restaurant':restaurant_list,
            'user_restaurant_list':loginUser_restaurant_list,
        }
        return render(request,'restaurant/admin_dashboard.html',context)

    elif request.method=='POST':
        form=UserForm(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            email=form.cleaned_data['email']
            password=form.cleaned_data['password']
            user.set_password(password)
            user.save()
            a=user
            a.created_by=request.user.email
            a.save()
            messages.success(request,"User has been succesfully created")
            return redirect('/admin-dashboard/')
        else:
            messages.warning(request,form.errors)
            return redirect('/admin-dashboard/')

@login_required
def subadminDashboard(request):
    if request.method=='GET':
        if request.user.is_authenticated:
            if not request.user.is_subadmin:
                if request.user.is_staff:
                    return redirect('/admin-dashboard/')
                else:
                    return redirect('/dashboard/')
        try:
            user_list=User.objects.filter(created_by=request.user.email).order_by('-date_joined')
            restaurant_list=Restaurant.objects.select_related('created_by').all().exclude(created_by=request.user).order_by('-created_at')
            loginUser_restaurant_list=Restaurant.objects.select_related('created_by').filter(created_by=request.user).order_by('-created_at')
            form=UserForm(request.POST or None)
        except Exception as e:
            return HttpResponse(e)
        context={
            'users':user_list,
            'form':form,
            'restaurant':restaurant_list,
            'user_restaurant_list':loginUser_restaurant_list
        }
        return render(request,'restaurant/admin_dashboard.html',context)

    elif request.method=='POST':
        form=UserForm(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            email=form.cleaned_data['email']
            password=form.cleaned_data['password']
            user.set_password(password)
            user.save()
            a=user
            a.created_by=request.user.email
            a.save()
            messages.success(request,"User has been succesfully created")
            return redirect('/admin-dashboard/')
        else:
            messages.warning(request,form.errors)
            return redirect('/admin-dashboard/')

# create subadmin
@login_required
def addToSubadmin(request,id):
    try:
        user=User.objects.get(pk=id)
        if user is not None:
            user.is_subadmin='True'
            user.save()
            messages.success(request,"User has been succesfully added to subadmin")
            return redirect('/admin-dashboard/') 
        else:
            messages.warning(request,'User not found')
            return redirect('/admin-dashboard/') 
    except Exception as e:
        return HttpResponse(e)
    
@login_required
def userDetail(request,id):
    if request.user.is_staff:
        users=get_object_or_404(User,pk=id)
        return render(request,'restaurant/userdetail.html',{'user':users})
    elif request.user.is_subadmin:
        users=get_object_or_404(User,pk=id,created_by=request.user.email)

restaurant/templates/restaurant/base.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!--Jquery CDN-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>{%block title%}{%endblock%}</title>
    {%block extra_style%}
    {%endblock%}
    <style> 
       .login_link{text-decoration: none;color: black;} 
       .register_link{text-decoration: none;color: white;}
       .item1 {background-color: #e3d105;border: 2px solid #e3d105;margin-right: 15px;}
       .item2 {background-color: transparent;border: 1px solid white;}
       .item2:hover{background-color: #e3d105;border: 1px solid black;color: black;}
       .register_link:hover{color: black;}
       .copyright{width: 100%;background-color:black;height: 80px;}
       .copyright h6{text-align: center;padding:25px;color: white;}
       
   </style>
  </head>
  <body>
    {%for message in messages %}
    <div class="alert alert-{{message.tags}} alert-dismissible">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        {{message}}
    </div>
    {%endfor%}
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container-fluid">
            {% if request.user.is_authenticated %}
            <a class="navbar-brand" href="/dashboard/"><img src="{%static 'images/logo.png'%}" alt=""></a>
            {%else%}
            <a class="navbar-brand" href="/"><img src="{%static 'images/logo.png'%}" alt=""></a>
            {%endif%}
            
            <ul class="list-group list-group-horizontal">
                
                {%if not request.user.is_authenticated %}
                <li class="list-group-item item1"><a href="{% url 'restaurant:login'%}" class="login_link" style="float:right;" >Login</a></li>
                <li class="list-group-item item2"><a href="{% url 'restaurant:register'%}" class="register_link" style="float:right;">Register</a></li>
                {%else%}
                    {%if request.user.is_staff%}
                        <li class="list-group-item"><a href="/admin-dashboard/"><i class="fas fa-home" style="color: black;"></i></a></li>
                        
                    {%elif request.user.is_subadmin %}
                        <li class="list-group-item"><a href="/subadmin-dashboard/"><i class="fas fa-home" style="color: black;"></i></a></li>
                    {%else%}
                        <li class="list-group-item"><a href="/dashboard/"><i class="fas fa-home" style="color: black;"></i></a></li>
                    {%endif%}


                    <div class="btn-group">
                        <button type="button" class="btn btn-danger dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="material-icons" style="font-size:px">settings</i>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#"><i class="fas fa-user-alt"></i> {{request.user.get_full_name}}</a></li>
                            {%if request.user.is_staff%}
                                <li><a class="dropdown-item" href="#">Admin</a></li>
                            {%elif request.user.is_subadmin %}
                                <li><a class="dropdown-item" href="#">Subadmin</a></li>
                            {%endif%}
                            <li><a class="dropdown-item" href="{% url 'restaurant:change_password' %}">Change Password</a></li>
                            
                        </ul>
                    </div>
                    <li class="list-group-item item1"><a href="{% url 'restaurant:logout'%}" class="login_link" style="float:right;" >Logout</a></li>
                   
                {%endif%}
            </ul>
          </div>
        </div>
    </nav>
    {%if request.user.is_authenticated %}
        <div class="container mt-5">
            <div class="row">
                <form action="{% url 'restaurant:search' %}">
                
                <div class="input-group mb-3">
                    {%if not request.user.is_staff %}
                    <select class="form-select-lg" style="width:25%" name="address">
                      <option selected value="">Choose from your address</option>
                       {% for address in request.user.address.all %}
                       <option value="{{address.id}}">{{address.address | truncatechars:20}} Pincode-{{address.pincode}}</option>
                       {%endfor%}
                    </select>
                    {%endif%}
                    <input type="text" required name="query" value="{{query}}" class="form-control" placeholder="Search a restaurant with name, city, food or pincode ">
                    <button class="btn btn-secondary" type="submit"><i class="fas fa-search"></i></button>
                </div> 
                </form> 
            </div>   
        </div>             
    {%endif%}
    {%block content%}
        
    {%endblock%}
    <div class="copyright">
        <div class="container">
            <h6>© 2021 All Rights Reserved.</h6>
        </div>
    </div>
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</html>

restaurant/templates/restaurant/food.html
{%extends 'restaurant/base.html'%}
{%load static%}
{%block title%}Add Restaurant{%endblock%}
{%block extra_style%}
    <style> 
        input{width:100%;padding: 8px;border: none;}
        label{font-weight: bold;}
        .error{font-weight: bold;}
        input:focus{border: none;}
        .submitBtn{background-color: #e3d105; border: 1px solid white; height: 50px;width:100px;padding: 10px;}
    </style>
{%endblock%}
{%block content%}
    <div class="container">
        <br><br>
        <div class="row">
            <h4><a href="{%url 'restaurant:dashboard'%}" style="text-decoration: none;">Home</a>/Restaurant/ {{restaurant.name}}</h4><br>
            <div class="col-md-3 mb-3 shadow ">
                <div class="card" style="margin-top: 20px;">
                    <img class="card-img-top" src="{{restaurant.image.url}}" alt="Card image" width="100%" height="200px">
                    <div class="card-body">
                        <h4 class="card-title">{{restaurant.name}}</h4>
                        <p class="card-text">{{restaurant.address}} Pincode -{{restaurant.pincode}}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-9 mb-3 shadow ">
                <h4 style="padding-top: 10px;">All Menu</h4>
                {%if request.user.is_staff or request.user.is_subadmin%}
                    {%if request.user == restaurant.created_by %}
                    {%if not current_food %}
                    <button  class="btn btn-primary" onclick="addFood()"  id="button-addon2"><i class="fas fa-plus"></i> Add Food</button>
                    {%endif%}
                    <br> <br>
                    {%if current_food %}
                    <!--update Food-->
                    <form action="" method="post" enctype="multipart/form-data">
                        {%csrf_token%}
                        <h5>Update Food {{current_food}}</h5>
                        {% for field in form%}
                        <div class="mb-3">
                        <span class="error">{{field.errors}}</span>
                        <label for="">{{field.label_tag}}</label>
                        <div class="form-control form-control-lg">{{field}}</div>
                        </div>
                        {%endfor%} <br>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                    {%endif%}
                    <!--Add Food-->
                    <form method="post" enctype="multipart/form-data">
                        {%csrf_token%}
                        <div class="row" id="food"> </div>
                        <input type="hidden" value="{{restaurant.id}}" name="id">
                        <button class="btn btn-info text-white" type="submit" id="AddFoodBtn">Add</button>
                    </form>
                    {%endif%}
                {%endif%}
                <hr>
                <div class="row">
                    {%if menu%}
                    {%for food in menu%}
                    <div class="col-md-4 mb-2">
                        <div class="card shadow">
                            <img class="card-img-top img-circle" src="{{food.image.url}}" alt="Card image" width="auto" height=""><hr>
                            <div class="card-body">
                                <h4 class="card-title">{{forloop.counter}}. {{food.name}}</h4>
                                <p><b>Price- &#x20B9; {{food.price}}</b></p>
                                <p class="card-text">{{food.description | truncatechars:30}}</p>
                                {%if not request.user.is_staff %}
                                    <button class="btn btn-primary">Add to Cart</button>
                                {%endif%}
                                {%if request.user.is_staff or request.user.is_subadmin %}
                                    {%if request.user == restaurant.created_by %}
                                    <a href="{% url 'restaurant:update-food' id=food.id%}"><button class="btn btn-info"><i class="fas fa-edit"></i></button></a>
                                    <a href="{% url 'restaurant:delete-food' id=food.id%}"><button class="btn btn-danger"><i class="fas fa-trash"></i></button></a>
                                    {%endif%}
                                {%endif%}
                            </div>
                        </div>
                    </div>
                    {%endfor%}
                    {%else%}
                        <h2>Sorry,No Food</h2>
                    {%endif%}
                </div>
                
            </div>
        </div>
    </div>
    
    <script>
        var current_food=0
        var i=0

        function hideAddFoodBtn() {  
            if(i > 0){
                $("#AddFoodBtn").show();
            }else{
                $("#AddFoodBtn").hide();
            }
        }
        hideAddFoodBtn()
        function addFood(){
            var element=document.getElementById('food')
            
            var html= ' <div class="input-group mb-3" id="current_food_'+current_food+'"><input type="text" class="form-control" name="foodName" required placeholder="Name" aria-describedby="button-addon2"><input type="text" required style="width:50px" class="form-control" name="price" placeholder="Price"><br><textarea row="2" required placeholder="Description" name="desc"></textarea><input type="file" name=image required><button class="btn btn-danger" onclick="removeFood('+current_food+')" type="button">Remove Food</button></div> '
            element.innerHTML +=html
            current_food ++
            i++
            hideAddFoodBtn()
        }
        function removeFood(id){
            var ele=document.getElementById('current_food_'+id+'')
            ele.remove()
            i--
            hideAddFoodBtn()
        }

    </script>
{%endblock%}

restaurant/templates/restaurant/userdetail.html
{%extends 'restaurant/base.html'%}
{%load static%}
{%block title%}{{user.get_full_name}} {{request.user.get_full_name}}{%endblock%}
{%block extra_style%}
    <style> 
       .error{color:red}
    </style>
{%endblock%}
{%block content%}
    <div class="container">
        <br>
        <h3>{{user.email}}</h3><br>
        <div class=" table-responsive">
            <table class="table table-striped">
                <tbody>
                <tr>
                    <th>Fullname</th>
                    <td>{{user.get_full_name}}</td>
                </tr>
               
                <tr>
                    <th>Email</th>
                    <td>{{user.email}}</td>
                </tr>
                <tr>
                    <th>Created Date</th>
                    <td>{{user.date_joined}}</td>
                </tr>
                {%if not request.user.is_subadmin %}
                <tr>
                    <th>Subadmin</th>
                    <td>
                        {%if user.is_subadmin %}
                        Yes
                        {%else%} 
                        No
                        {%endif%}
                    </td>
                </tr>
                <tr>
                    <th>Created By</th>
                    <td>
                        {%if user.created_by == request.user.email  %}
                        Me
                        {%else%} 
                        {{user.created_by}}
                        {%endif%}
                    </td>
                </tr>
                {%endif%}
                <tr>
                    <th><a href="{% url 'restaurant:delete-user' id=user.id %}">Delete</a></th>
                </tr>
                
                </tbody>
              </table>
        </div>
        <br> <h5>Addresses</h5>
        <table class="table"> 
            {%if user.address.all%}
            <tbody>
                <tr>
                    <th>Sr No.</th>
                    <th>Address</th>
                </tr>
                    {%for address in user.address.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><address>{{address.address}}</address></td>
                    </tr>
                    {%endfor%}
            </tbody>
            {%else%}
                <p>User has no Address</p>
            {%endif%}
        </table>
        {%if user.is_subadmin %}
        <div class="row">
            <h4>Restaurant of Subadmin</h4>
            {%if user.restaurant_set.all %}
            {%for r in user.restaurant_set.all%}
            <div class="col-md-4">
                <div class="card">
                    <img class="card-img-top" src="{{r.image.url}}" alt="Card image" width="auto" height="200px">
                    <div class="card-body">
                      <h4 class="card-title">{{r.name.upper}}</h4>
                      <p class="card-text">{{r.address | truncatechars:30}}</p>
                      <a href="{% url 'restaurant:menu' resID=r.id %}" style="text-decoration: none;color: white;"><button class="btn btn-success">View Menu</button></a><br>
                    </div>
                  </div>
            </div>
            {%endfor%}
            {%else%}
                <h6>No Restaurant added.</h6>
            {%endif%}
        </div>
        {%endif%}
    </div>
{%endblock%}